<?php

// DO NOT EDIT THIS FILE
// This file has been generated using the genlang.php script. You should edit
// lang.csv and run genlang.php again.

$g_locales_strings = array (
  'about' => 
  array (
    'en' => 'about',
    'fr' => 'à propos',
  ),
  'add-debt' => 
  array (
    'en' => 'add debt',
    'fr' => 'ajouter une dette',
  ),
  'add-debt-desc' => 
  array (
    'en' => 'This form allows you to add a debt. After you submitted the debt, the other concerned user will have to confirm the new debt.',
    'fr' => 'Ce formulaire permet d\'ajouter une dette. Après avoir ajouté la dette, l\'autre utilisateur concerné deva confirmer l\'ajout de la dette.',
  ),
  'add-user' => 
  array (
    'en' => 'add a friend',
    'fr' => 'ajouter un ami',
  ),
  'add-user-to-friends' => 
  array (
    'en' => 'add a user to my friends',
    'fr' => 'ajouter un utilisateur à mes amis',
  ),
  'adddebt' => 
  array (
    'en' => 'add debt',
    'fr' => 'ajouter une dette',
  ),
  'amount' => 
  array (
    'en' => 'amount',
    'fr' => 'montant',
  ),
  'avatar' => 
  array (
    'en' => 'avatar',
    'fr' => 'avatar',
  ),
  'cococo' => 
  array (
    'en' => 'cococo',
    'fr' => 'cococo',
  ),
  'contact-us' => 
  array (
    'en' => 'contact us',
    'fr' => 'Contactez-nous',
  ),
  'current-avatar' => 
  array (
    'en' => 'current avatar',
    'fr' => 'avatar actuel',
  ),
  'date-format-desc' => 
  array (
    'en' => 'date format: YYYY-MM-DD',
    'fr' => 'format de date: YYYY-MM-DD',
  ),
  'debt-date' => 
  array (
    'en' => 'date of the debt',
    'fr' => 'date de la dette',
  ),
  'description' => 
  array (
    'en' => 'description',
    'fr' => 'description',
  ),
  'email' => 
  array (
    'en' => 'email',
    'fr' => 'courriel',
  ),
  'favs' => 
  array (
    'en' => 'my friends',
    'fr' => 'mes amis',
  ),
  'first-name' => 
  array (
    'en' => 'first name',
    'fr' => 'prénom',
  ),
  'go_login' => 
  array (
    'en' => 'login',
    'fr' => 'connexion',
  ),
  'hide-show-favs' => 
  array (
    'en' => 'hide / show friends',
    'fr' => 'afficher / cacher mes amis',
  ),
  'history' => 
  array (
    'en' => 'history',
    'fr' => 'historique',
  ),
  'i-owe-them' => 
  array (
    'en' => 'i owe them',
    'fr' => 'je dois',
  ),
  'image-will-be-resized-to-48px' => 
  array (
    'en' => 'the image will be resized to 48px',
    'fr' => 'l\'image sera redimensionnée à 48px',
  ),
  'it-is-a-refund' => 
  array (
    'en' => 'it is a refund',
    'fr' => 'il s\'agit d\'un remboursement',
  ),
  'language' => 
  array (
    'en' => 'language',
    'fr' => 'langue',
  ),
  'last-name' => 
  array (
    'en' => 'last name',
    'fr' => 'nom de famille',
  ),
  'logout' => 
  array (
    'en' => 'logout',
    'fr' => 'déconnexion',
  ),
  'modify' => 
  array (
    'en' => 'modify',
    'fr' => 'modifier',
  ),
  'my-cococo' => 
  array (
    'en' => 'my cococo',
    'fr' => 'mon cococo',
  ),
  'my-friends' => 
  array (
    'en' => 'my friends',
    'fr' => 'mes amis',
  ),
  'my-friends-desc' => 
  array (
    'en' => 'Your friends are a set of users that are easily accessible when you need to add a debt of perform other operations on this site.',
    'fr' => 'Vos amis sont un ensemble d\'utilisateurs facilement accessibles pour l\'ajout de dettes et d\'autres opérations sur le système.',
  ),
  'my-profile' => 
  array (
    'en' => 'my profile',
    'fr' => 'mon profil',
  ),
  'my-profile-desc' => 
  array (
    'en' => 'The fields are modified as soon as they loose focus (when you click outside them).',
    'fr' => 'Les champs sont modifiés dès que vous cliquez à l\'extérieur.',
  ),
  'new-avatar' => 
  array (
    'en' => 'new avatar',
    'fr' => 'nouvel avatar',
  ),
  'new-password' => 
  array (
    'en' => 'new password',
    'fr' => 'nouveau mot de passe',
  ),
  'new-password-confirm' => 
  array (
    'en' => 'new password (confirm)',
    'fr' => 'nouveau mot de passe (encore)',
  ),
  'optional' => 
  array (
    'en' => 'optional',
    'fr' => 'optionnel',
  ),
  'other-person' => 
  array (
    'en' => 'other person',
    'fr' => 'autre personne',
  ),
  'password' => 
  array (
    'en' => 'password',
    'fr' => 'mot de passe',
  ),
  'profile' => 
  array (
    'en' => 'my profile',
    'fr' => 'mon profil',
  ),
  'refund' => 
  array (
    'en' => 'refund',
    'fr' => 'remboursement',
  ),
  'search' => 
  array (
    'en' => 'search',
    'fr' => 'rechercher',
  ),
  'search-user' => 
  array (
    'en' => 'search user',
    'fr' => 'rechercher un utilisateur',
  ),
  'send' => 
  array (
    'en' => 'send',
    'fr' => 'envoyer',
  ),
  'signup' => 
  array (
    'en' => 'signup',
    'fr' => 'inscription',
  ),
  'summary' => 
  array (
    'en' => 'summary',
    'fr' => 'sommaire',
  ),
  'they-owe-me' => 
  array (
    'en' => 'they owe me',
    'fr' => 'on me doit',
  ),
  'totals' => 
  array (
    'en' => 'totals',
    'fr' => 'totaux',
  ),
  'username' => 
  array (
    'en' => 'username',
    'fr' => 'nom d\'utilisateur',
  ),
  'value-invalid' => 
  array (
    'en' => 'invalid value...',
    'fr' => 'valeur invalide...',
  ),
  'value-modified' => 
  array (
    'en' => 'value saved !',
    'fr' => 'valeur modifiée !',
  ),
  'welcome' => 
  array (
    'en' => 'welcome on cococo !',
    'fr' => 'bienvenue sur cococo !',
  ),
  'welcome-intro' => 
  array (
    'en' => '<strong>cococo</strong> is a debt management system that helps you track who owes you some money and vice-versa.
Start tracking your debts in only 3 easy steps:',
    'fr' => '<strong>cococo</strong> est un système de gestion de dettes interpersonnelles qui vous aide à vous rappeler qui vous doit combien depuis quand, et vice versa, combien vous devez à qui depuis quand. Commencez dès maintenant en quelques étapes :',
  ),
  'which-way' => 
  array (
    'en' => 'which way ?',
    'fr' => 'quel sens ?',
  ),
);

?>